export enum MessageTypes {
    INDENT = 'INDENT',
    PRIVATE_MESSAGE = 'PRIVATE.MESSAGE',
    NEW_USER = 'NEW.USER',
    WELCOME = 'WELCOME',
    CLOSED_SESSION = 'CLOSED.SESSION',
}

export enum MessageTypesGames {
    GAME_START = 'GAME.START',
    GAME_UPDATE_MATCH = 'GAME.UPDATE.MATCH',
    GAME_MOVEMENTS_MADE = 'GAME.MOVEMENTS.MADE',
    ERROR_OCCURRED = 'ERROR.OCCURRED',
    GAME_SECOND_PLAYER_ADDED = 'GAME.SECOND.PLAYER.ADDED',
    LEFT_MATCH = 'LEFT.MATCH',
    GAME_END = 'GAME.END'
}

export enum GameType {
    MASTER_MIND = 'MasterMind',
    FOUR_IN_LINE = 'FourInLine'
}